// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUi3hQifmAG_Xgcf2ClNi5UM2DXjCcwTA',
    appId: '1:342229509705:web:35898ec993f6dd77be4198',
    messagingSenderId: '342229509705',
    projectId: 'lecalo',
    authDomain: 'lecalo.firebaseapp.com',
    storageBucket: 'lecalo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp6DCBrz8u-Fk3HFIESzvfvbDZ9THxoRo',
    appId: '1:342229509705:android:400022ded8bce42cbe4198',
    messagingSenderId: '342229509705',
    projectId: 'lecalo',
    storageBucket: 'lecalo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3naT5cBVdiFoLQGeqIaDN6cbUEs27bPI',
    appId: '1:342229509705:ios:8e6d85129f8d3c0abe4198',
    messagingSenderId: '342229509705',
    projectId: 'lecalo',
    storageBucket: 'lecalo.appspot.com',
    iosBundleId: 'com.example.lecalo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3naT5cBVdiFoLQGeqIaDN6cbUEs27bPI',
    appId: '1:342229509705:ios:30d6f21266bd7cdabe4198',
    messagingSenderId: '342229509705',
    projectId: 'lecalo',
    storageBucket: 'lecalo.appspot.com',
    iosBundleId: 'com.example.lecalo.RunnerTests',
  );
}
